// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezakimuqshxoyxozkmfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6YWtpbXVxc2h4b3l4b3prbWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMTU1MTMsImV4cCI6MjA0OTY5MTUxM30.xdNjZAQUcrWyaX_8b_gVHBh0hOPWK5_J7JqwyKJirD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);